name: dispose
description: A handler to correctly dispose listeners, timers, controllers and etc.
homepage: https://github.com/jodinathan/dispose
version: 0.0.1

environment:
  sdk: '>= 2.4.0 < 3.0.0'

dependencies:
  angular: ^5.3.1
  pedantic: ^1.9.2