name: dispose
description: A handler to correctly dispose listeners, timers, controllers etc.
homepage: https://github.com/jodinathan/dispose
version: 0.0.8

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ngdart: ^7.1.1
  change_notifier: ^0.24.0
  tuple: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
