name: dispose
description: A handler to correctly dispose listeners, timers, controllers etc.
homepage: https://github.com/jodinathan/dispose
version: 0.0.9+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  ngdart: ^8.0.0-dev.2
  change_notifier: ^0.24.0
  tuple: ^2.0.0
  meta: ^1.9.0

dev_dependencies:
  lints: ^2.0.0
