name: dispose
description: A handler to correctly dispose listeners, timers, controllers etc.
homepage: https://github.com/jodinathan/dispose
version: 0.0.6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  lints: ^1.0.1
